# Generated by Django 3.0 on 2020-04-27 07:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Company', models.CharField(max_length=89)),
                ('Adhar_Number', models.CharField(default='Adhar Number', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('Phone_Number', models.CharField(default='Mobile Number', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('GST_Number', models.CharField(max_length=15)),
                ('Pan_Number', models.CharField(default='PAN Number', max_length=10)),
                ('CIN_Number', models.CharField(max_length=21)),
                ('Company_Postal_Address', models.CharField(default='Complete Address', max_length=89)),
                ('Bank_Account_Number', models.CharField(default='Bank Account Number', max_length=12)),
                ('IFSC', models.CharField(default='IFSC CODE', max_length=11)),
                ('Branch', models.CharField(default='Branch Name', max_length=29)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
