# Generated by Django 3.0.8 on 2020-08-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200504_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
