# Generated by Django 3.0 on 2020-09-25 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=129)),
                ('Email', models.EmailField(max_length=159)),
                ('Phone', models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('Journey_Date', models.DateField(default='')),
                ('Destination', models.CharField(max_length=129)),
                ('Adults', models.PositiveIntegerField(default=0, help_text='People')),
            ],
        ),
    ]
