# Generated by Django 3.0 on 2020-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays_Packages_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='HolidayPackage_Images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
