# Generated by Django 3.0 on 2020-10-05 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central_Asia_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/CentralAsia/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domestic_Holiday_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/Domestic/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Europe_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/Europe/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=159)),
                ('Phone', models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('Email', models.EmailField(default='', max_length=159)),
                ('From', models.CharField(max_length=199)),
                ('To', models.CharField(max_length=199)),
                ('Date', models.DateField()),
                ('Till_Date', models.DateField(blank=True, null=True)),
                ('Class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business')], max_length=89)),
                ('Adults', models.PositiveIntegerField(default=0)),
                ('Children', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays_Packages_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=159)),
                ('Phone', models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('Email', models.EmailField(max_length=159)),
                ('Destination', models.CharField(max_length=199)),
                ('Check_In', models.DateField()),
                ('Check_Out', models.DateField(blank=True, null=True)),
                ('Class', models.CharField(choices=[('Economy', 'Economy'), ('3-Star', '3-Star'), ('4-Star', '4-Star'), ('5-Star', '5-Star')], max_length=89)),
                ('Adults', models.PositiveIntegerField(default=0)),
                ('Children', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Rooms', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Middle_East_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/MiddleEast/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SouthEast_Asia_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/SouthEast_Asia/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=159)),
                ('Phone', models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('Email', models.EmailField(max_length=159)),
                ('Journey_By', models.CharField(choices=[('Train', 'Train'), ('Bus', 'Bus'), ('Others', 'Others')], default='', max_length=129)),
                ('Departure', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visa_Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=159)),
                ('Phone', models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')])),
                ('Email', models.EmailField(max_length=159)),
                ('Country', models.CharField(max_length=159)),
                ('Duration', models.CharField(choices=[('1', '1-Month'), ('2', '2-Months'), ('3', '3-Months')], max_length=129)),
            ],
        ),
    ]
