# Generated by Django 3.0 on 2020-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays_packages_upload',
            name='Location_Image',
            field=models.FileField(upload_to='media/HolidayPackage_Images/'),
        ),
    ]
