# Generated by Django 3.0 on 2020-10-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport_Services',
        ),
    ]
