# Generated by Django 3.0 on 2020-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0002_auto_20200928_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays_packages_upload',
            name='Package',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='', max_length=59),
        ),
    ]
