# Generated by Django 3.0 on 2020-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0003_holidays_packages_upload_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic_Holiday_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/Domestic/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
