# Generated by Django 3.0 on 2020-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0003_transports_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transports_enquiry',
            name='Destination',
            field=models.CharField(default='', max_length=129),
        ),
    ]
