# Generated by Django 3.0 on 2020-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0004_domestic_holiday_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Central_Asia_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/CentralAsia/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'CentralAsia'), ('Europe', 'Europe'), ('MiddleEast', 'MiddleEast'), ('SouthEast_Asia', 'SouthEast_Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='domestic_holiday_package',
            name='Package',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'CentralAsia'), ('Europe', 'Europe'), ('MiddleEast', 'MiddleEast'), ('SouthEast_Asia', 'SouthEast_Asia')], default='', max_length=59),
        ),
        migrations.AlterField(
            model_name='holidays_packages_upload',
            name='Package',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'CentralAsia'), ('Europe', 'Europe'), ('MiddleEast', 'MiddleEast'), ('SouthEast_Asia', 'SouthEast_Asia')], default='', max_length=59),
        ),
    ]
