# Generated by Django 3.0 on 2020-10-06 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0004_transports_enquiry_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='transports_enquiry',
            name='Return_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
