# Generated by Django 3.0 on 2020-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0005_auto_20200929_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central_asia_packages',
            name='Package',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59),
        ),
        migrations.AlterField(
            model_name='domestic_holiday_package',
            name='Package',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59),
        ),
        migrations.AlterField(
            model_name='holidays_packages_upload',
            name='Package',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59),
        ),
    ]
