# Generated by Django 3.0 on 2020-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0007_europe_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Middle_East_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_Name', models.CharField(max_length=255)),
                ('Days', models.PositiveIntegerField()),
                ('Nights', models.PositiveIntegerField()),
                ('Datailed_Itinerary', models.TextField()),
                ('Location_Image', models.FileField(upload_to='media/MiddleEast/HolidayPackage_Images/')),
                ('Package', models.CharField(choices=[('Domestic', 'Domestic'), ('CentralAsia', 'Central-Asia'), ('Europe', 'Europe'), ('MiddleEast', 'Middle-East'), ('SouthEast_Asia', 'SouthEast-Asia')], default='', max_length=59)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
