# Generated by Django 3.0 on 2020-10-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0009_southeast_asia_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=199)),
                ('To', models.CharField(max_length=199)),
                ('Date', models.DateField()),
                ('Till_Date', models.DateField()),
                ('Class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business')], max_length=89)),
                ('Adults', models.PositiveIntegerField()),
                ('Children', models.PositiveIntegerField()),
            ],
        ),
    ]
