# Generated by Django 3.0 on 2020-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0010_flight_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='Till_Date',
            field=models.DateField(blank=True),
        ),
    ]
