# Generated by Django 3.0 on 2020-10-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0011_auto_20201002_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='Till_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
