# Generated by Django 3.0 on 2020-10-02 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0012_auto_20201002_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_booking',
            name='Name',
            field=models.CharField(default='', max_length=159),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='Phone',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
        ),
    ]
