# Generated by Django 3.0 on 2020-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0013_auto_20201002_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='Children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
