# Generated by Django 3.0 on 2020-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0014_auto_20201002_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking',
            name='Adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight_booking',
            name='Children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
